#
# Ce fichier contient les balises de configuration pour personnaliser votre site
#

# Nom de votre site (affiché dans le header)
name: Votre Nom

# Bio rapide ou description (affichée dans le header)
description: Développeur Web de Quelque Part

# URL de votre avatar ou photo de profil (vous pourriez utiliser votre photo de profil GitHub)
avatar: https://raw.githubusercontent.com/barryclark/jekyll-now/master/images/jekyll-logo.png

#
# Les balises ci-dessous sont facultatives
#

# Ajoute une icône dans le pied de page pour chaque nom d'utilisateur que vous entrez
footer-links:
  dribbble: 
  email: 
  facebook: 
  flickr: 
  github: christopheducamp/jekyll-now
  instagram: 
  linkedin: 
  pinterest: 
  rss: # tapez juste ici ce que vous voulez pour une icône RSS, assurez vous d'avoir réglé l'url au-dessus ! 
  twitter: jekyllrb

# Votre nom d'utilisateur disqs, entrer ça permettra les commentaires sur les posts
disqus: 

# Entrez votre code de suivi Google Analytics (par ex. UA-2110908-2) pour activer le suivi
google_analytics: 

# Votre URL de site web (par ex. http://barryclark.github.io ou http://www.barryclark.co)
# Utilisé pour Sitemap.xml et votre flux RSS
url: http://christopheducamp.github.io

# Si vous hébergez votre site sur un repository Project sur les Pages GitHub
# (http://votrenomutilisateur.github.io/nom-repository)
# et NON PAS votre repository d'utilisateur (http://votrenomutilisateur.github.io)
# puis ajoutez-ici l'url-base, comme ceci : "/nom-repository"
baseurl: "/jekyll-now"

#
# !! Vous n'avez pas besoin de modifier quelque balise de configuration en-dessous !!
#

markdown: kramdown
highlighter: pygments
permalink: /:title

# La version de Jekyll Now que vous utilisez à cette heure
version: v1.0.0

# Régler le répertoire Sass partiel, car nous utilisons @imports
sass:
  sass_dir: _scss
  style: :expanded # Vous pourriez préférer minimiser en utilisant :compressed

# Utilise les plugins suivants
gems:
  - jemoji # Emoji SVP !
  - jekyll-sitemap # Crée un sitemap en utilisant la gem officiellle de Jekyll

# Excluez ces fichiers de votre _site de production
exclude:
    - Gemfile
    - Gemfile.lock
    - LICENSE
    - README.md